const actionTypes = {
  GET_DATA_START: "GET_DATA_START",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAILURE: "GET_DATA_FAILURE",
  ADD_TO_CARD: "ADD_TO_CARD",
  REMOVE_TO_CARD: "REMOVE_TO_CARD",
  UPDATED_AMOUNT: "UPDATED_AMOUNT",
  GET_CATEGORIE_START: "GET_CATEGORIE_START",
  GET_CATEGORIE_SUCCESS: "GET_CATEGORIE_SUCCESS",
  GET_CATEGORIE_FAILURE: "GET_CATEGORIE_FAILURE",
  GET_ROUT_START: "GET_CATEGORIE_START",
  GET_ROUT_SUCCESS: "GET_CATEGORIE_START",
  GET_ROUT_FAILURE: "GET_CATEGORIE_START",
};
export default actionTypes;
